server:
  port: 8181
  
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  
  appInfo:
    replicate:
      interval: 3
    initial:
      replicate:
        time: 3      